### PR TITLE
feat: add header and footer

### PR DESCRIPTION
**Pull request by gagaswin**
I created a header and footer, please review, sir.

### CODE REVIEW

**Comment by fundayluck** [comment]
image

pas di scroll headbar nya ga fix mas @GagasWahyu27,

**Comment by gagaswin** [comment]
Oh iya lupa

**Comment by gagaswin** [comment]
udah bener nih, mr.afan @fundayluck

**Review by fundayluck — APPROVED** [review]
LGTM

**Comment by gagaswin** [comment]
LGTM apa pan

**Pull request merged**
